{% set data = load_setup_py_data() %}
{% set version = environ.get("GIT_DESCRIBE_TAG").lstrip("v") %}

package:
  name: openmdao-nsga
  version: "{{ version }}"

about:
  home: https://github.com/ovidner/openmdao-nsga
  license: MIT
  license_file: LICENSE

source:
  git_url: ../

build:
  noarch: python
  script: "python -m pip install . --no-deps --ignore-installed -vv "
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - python
    - pip
    - setuptools-scm
  run:
    - deap
    - numpy
    - openmdao
    - pydoe2
    - pygmo
    - python

test:
  imports:
    - omnsga
